baseurl: "/portfolio"
url:     "https://nicollinoxx.github.io"

#----------------------------------------------------------------------
title:  "Portfolio"

avatar: "attachments/avatar/profile-photo.jpeg" #profile picture for portfolio
name:   "Nícolas Amaral"

#add here the technologies and tools you use
tools:
  - "Ruby"
  - "Ruby on Rails"
  - "SQLite"
  - "PostgreSQL"
  - "Bootstrap"
  - "Tailwind"

introduction: "Olá, seja bem-vindo! Este portfólio reúne alguns dos projetos que desenvolvi ao longo da minha jornada como desenvolvedor.
              Caso queira saber mais detalhes sobre algum deles, visite meu <a href='/'>Blog</a>, onde compartilho insights,
              experiências e um pouco do processo de desenvolvimento de cada projeto."

social_username:
  twitter-x: "Nícolas"
  linkedin:  "Nícolas Amaral"
  email:     "nicolasalmeida321@gmail.com"
  github:    "nicollinoxx"

social_link:
  twitter-x: "https://x.com/nicollinoxx"
  linkedin:  "https://www.linkedin.com/in/n%C3%ADcolas-amaral/"
  github:    "https://github.com/nicollinoxx"
  email:     nicolasalmeida321@gmail.com
#--------------------------------------------------------------------

collections:
  projects:
    output: true

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
