baseurl: "/portfolio"
url: "https://nicollinoxx.github.io"

#----------------------------------------------------------------------
title:  "Portfolio"

avatar: "attachments/avatar/example.jpeg" #profile picture for portfolio
name:   "Name"

#add here the technologies and tools you use
tools:
  - "Jekyll"
  - "Ruby"
  - "Python"
  - "Lua"
  - "Bootstrap"
  - "Tailwind"

introduction: "Add a stylish intro to your portfolio profile section"

social_username:
  twitter-x: "twitter username"
  linkedin:  "linkedin username"
  email:     "email username"
  github:    "github username"

social_link:
  twitter-x: "https://x.com"
  linkedin:  "https://www.linkedin.com"
  github:    "https://github.com"
  email:     "your-email@example.com"
#--------------------------------------------------------------------

collections:
  projects:
    output: true

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
